name = "Orchard SMP"
author = "SquirrelKiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f743a61caf6a7ddf49c1e3d600416b0b05c149710534837faa737463a54a9a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
