name = "Orchard SMP"
author = "SquirrelKiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1caba11701302b3ace15b820866d4779c7f7b88366df85fb2d8595315d4260a3"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
