name = "Orchard SMP"
author = "SquirrelKiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c082f9d470a76f9c24686ec6929da69df5c816d7f4700ead63d4e3cc58825136"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
