name = "Orchard SMP"
author = "SquirrelKiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8006538a76db70b5334e4426ccfb4dd1bc6c05408281db7a3adca4e22bae711f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
